spring.application.name=Fast-and-Furious-Food
spring.output.ansi.enabled=always
spring.profiles.active=test
#spring.profiles.active=prod
app.jwt.secret=rzbolcnV4R624B3ujHFqEX1MHXBxpSzH5WDHsMsHBMBkIsQ46ufnWo42YsE0HTw91i4BM96q3ePTaEHZSXpfWw==